export const STORES = [
    { id: '1', name: 'Mini | Santa | Loja 1', manager: 'Jaqueline' },
    { id: '1', name: 'Salvados | Santa | Loja 1', manager: 'Valquíria' },
    { id: '2', name: 'Mini | Torres | Loja 2', manager: 'Rosimar Robison' },
    { id: '2', name: 'Salvados | Torres | Loja 2', manager: 'Lucas Pego' },
    { id: '3', name: 'Centro de Distribuição | Loja 3', manager: '' },
    { id: '4', name: 'Mini | Pinhais | Loja 4', manager: 'Michele' },
    { id: '4', name: 'Salvados | Pinhais | Loja 4', manager: 'Carlos Eduardo' },
    { id: '5', name: 'Ecommerce | Loja 5', manager: 'Marcos Cardoso' },
    { id: '6', name: 'Mini | Paranaguá | Loja 6', manager: 'Dennis Keller' },
    { id: '6', name: 'Salvados | Paranaguá | Loja 6', manager: 'Dennis Keller' },
    { id: '7', name: 'Mini | Fanny | Loja 7', manager: 'Ivan Nícássio' },
    { id: '8', name: 'Mini | Fazenda Rio Grande | Loja 8', manager: 'Sheila' },
    { id: '8', name: 'Salvados | Fazenda Rio Grande | Loja 8', manager: 'Sheila' },
    { id: '10', name: 'Mini | Xaxim | Lo_ja 10', manager: 'Maria Franciely' },
    { id: '10', name: 'Salvados | Xaxim | Loja 10', manager: 'Maria Franciely' },
    { id: '11', name: 'Mini | Fazendinha | Loja 11', manager: 'Jorge Belotto' },
    { id: '11', name: 'Salvados | Fazendinha | Loja 11', manager: 'Gabriele Fernandes' },
    { id: '12', name: 'Mini | Boulevard | Loja 12', manager: 'Anderson Oliveira' },
    { id: '14', name: 'Mini | Colombo | Loja 14', manager: 'Diego' },
    { id: '14', name: 'Salvados | Colombo | Loja 14', manager: 'Diego' },
    { id: '17', name: 'Salvados | Xaxim | Loja 17', manager: 'Maria Franciely' },
    { id: '18', name: 'Salvados | Fanny | Loja 18', manager: 'Luiz Traldi' },
    { id: '19', name: 'Mini | Araucária | Loja 19', manager: 'Orli Tadeu' },
    { id: '19', name: 'Salvados | Araucária | Loja 19', manager: 'Orli Tadeu' },
    { id: 'BACACHERI', name: 'Mini | Bacacheri', manager: 'Eduardo' },
    { id: '201', name: 'Salvados | Bal Camboriú | Loja 201', manager: 'João Paiva' },
    { id: '202', name: 'Salvados | Itajaí | Loja 202', manager: 'Thiago' },
    { id: '206', name: 'Araquari | Loja 206', manager: 'Márcio Fernandes' },
    { id: '208', name: 'Joinville | Loja 208', manager: 'Huanderson' },
    { id: '301', name: 'Mini | Vila Velha | Loja 301', manager: 'Marco Antonio' },
    { id: '303', name: 'Mini | Serra | Loja 303', manager: 'Erika' },
    { id: '304', name: 'Mini | Vitória | Loja 304', manager: 'Leonardo' },
    { id: '305', name: 'Linhares | Loja 305', manager: 'Suelen' },
    { id: '306', name: 'Mini | CD ES | Loja 306', manager: 'Dani Nascimento' },
    { id: '307', name: 'Mini | Glória | Loja 307', manager: 'Rackilane' },
    { id: '308', name: 'Mini | Day by Day | Loja 308', manager: 'Namar' },
];
